### ISSUE TITLE
Best Practice for Token Management and Caching

### ISSUE THREAD

**Issue by jakuste136** [nayanAubie/msal_auth#13]
I'm seeking advice on the recommended flow for using the package in a typical Flutter application scenario.

In my application, I need to access a protected API and send an access token with every request. I can acquire a token interactively using the acquireToken() function. However, I'm uncertain about the next steps. Should I cache the token (or the entire MsalUser object) in secure local storage, or is there a built-in function for this purpose?

I understand that acquireTokenSilent() is used for refreshing an expired token, not for retrieving a valid token from the cache.

Could you please clarify the best practice for managing tokens in this context?

Thank you in advance for your help.

**Comment by nayanAubie** [comment]
The best process is to store the `MsalUser` object. in your RESTful API, you should access the token from storage only. Before accessing the token, you'll need to call the below snippet.

```dart
// Don't call "acquireTokenSilent" if token is not expired.
    if (msalUser != null &&
        msalUser!.tokenExpiresOn > DateTime.now().millisecondsSinceEpoch) {
      return;
    }

final user = await _msalAuth?.acquireTokenSilent();
      if (user != null) {
// save the new user to local storage.
}
```

**Comment by jakuste136** [comment]
I guess that answers my question, thanks
