### ISSUE TITLE
Keeping user signed into application

### ISSUE THREAD

**Issue by paulhwangfti** [nayanAubie/msal_auth#15]
Hi, I was curious what the process would look like for trying to keep a user signed in between app sessions (like if the user closes out the app and comes back, they shouldn't need to have to sign back in).

The way that I currently had it set up was that every time that the app boots up, I check to see that the user has signed in before by checking if a token is stored on their device via secure storage. I don't check if it's expired and instead simply just call the `acquireTokenSilent().` This generally hasn't ran into any issues and simply would return a token that I've made in the past if it hasn't expired yet (at least I believe).

But it feels wrong because if the token hasn't expired yet, should I still be calling `acquireTokenSilent()` upon the app loading up? Is checking that the token has expired / is close to expiring just used for when making API calls / accessing resources with that authentication token?

Here's my current workflow to give you an idea:
```
Future<void> _init() async {
    _authority =
        'https://login.microsoftonline.com/$tenantId/oauth2/v2.0/authorize';
    _msalAuth = await getMsalAuth();

    try {
      if (await userHasBeenSignedInBefore()) {
        // User has signed in before (we know by checking that a key exists in the secure storage), get new token silently
        // Do we call acquireTokenSilent() if the token hasn't expired? Instead, do we just use the token stored in secure storage (that's not expired)
        // msal_auth refreshes a token via acquireTokenSilent(), see: https://github.com/nayanAubie/msal_auth/issues/12#issuecomment-2191627392
        await getTokenSilently();
        ...
      } else {
        // User has not signed in before (no token present in secure storage) -- user will have to sign in
        _isAuthenticated = false;
      }
    } catch (e) {
      ...
    } finally {
      ...
    }
  }
```

**Comment by nayanAubie** [comment]
@paulhwangfti There is a way to check whether the token is expired. mentioned in the `Readme` please check it. https://pub.dev/packages/msal_auth#get-auth-token-by-silent-call--when-expired

So when your token is expired, your app is supposed to call the `acquireTokenSilent` method.
