### ISSUE TITLE
Implement login_hint

### ISSUE THREAD

**Issue by colonelpopcorn** [nayanAubie/msal_auth#16]
Currently there is no way to inject a login_hint to the URL that gets opened. Could you add this in a future release? Would you be open to accepting a PR?

https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-oapx/a8622e66-2285-43c0-bbb9-abfcecdaed86

**Comment by nayanAubie** [comment]
I need to check more details. but yes, I am open to accepting a PR. you can create it. 👍

**Comment by colonelpopcorn** [comment]
I've opened PR #18 to address this issue.
