### ISSUE TITLE
`select_account` prompt value allowed?

### ISSUE THREAD

**Issue by paulhwangfti** [nayanAubie/msal_auth#22]
I was curious on whether or not the `select_account` value is able to be selected for `prompt` type, allowing for the user to simply select their account like below.

![image](https://github.com/user-attachments/assets/0b217073-b188-4445-98cb-966821871819)

See here:
https://learn.microsoft.com/en-us/entra/identity-platform/msal-js-prompt-behavior

**Comment by nayanAubie** [comment]
@paulhwangfti Yes, it is possible, I can update it within a few days else PR is welcome 🤗

**Comment by nayanAubie** [comment]
@paulhwangfti Fixed in version `2.2.0`
