### ISSUE TITLE
Error trying to get token

### ISSUE THREAD

**Issue by Whiz4655** [nayanAubie/msal_auth#24]
I keep getting activity cannot be null or empty

**Comment by grantv-outie** [comment]
If this is in your Android build, check `MainActivity.kt`, it should be:
   `class MainActivity: FlutterActivity()`
Mine was `FlutterFragmentActivity`, which was causing this error.

**Comment by nayanAubie** [comment]
Please go through the documentation else provide the complete details.

**Comment by grantv-outie** [comment]
I was getting this error on Android because I was using the `local_auth` package, which requires `FlutterFragmentActivity` in `MainActivity.kt`. This package works if the main activity is `FlutterActivity`. Can `msal_auth` support `FlutterFragmentActivity`?
