### ISSUE TITLE
IOS - webview login pending

### ISSUE THREAD

**Issue by amanzetti** [nayanAubie/msal_auth#26]
I'm able to complete login with android and take token.
With iOS, the webview start, but after that I insert email and password the page is pending forever.
Could you help me?

**Comment by paolomastinu** [comment]
I had the same problem,

you have to replace this code in ios->Runner->AppDelegate.swift

`import Flutter
import UIKit

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
`

with this one:

`import Flutter
import MSAL
import UIKit
 
@main
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
   override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
 
    return MSALPublicClientApplication.handleMSALResponse(url, sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String)
    }
}
`

**Comment by nayanAubie** [comment]
@amanzetti I've updated README in version `2.1.1`. @paolomastinu thanks for the code.
