### ISSUE TITLE
iOS - Unable to create MSALPublicClientApplication

### ISSUE THREAD

**Issue by levmorgot** [nayanAubie/msal_auth#29]
I handle PlatformException(AUTH_ERROR, Unable to create MSALPublicClientApplication, null, null) in iOS platform

```
final msalAuth = await MsalAuth.createPublicClientApplication(
        clientId: 'clientId',
        scopes: <String>[
          'https://graph.microsoft.com/user.read',
        ],
        androidConfig: AndroidConfig(
          configFilePath: Assets.configs.msalConfig,
        ),
        iosConfig: IosConfig(
          authority: 'https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/authorize',
  
          authMiddleware: AuthMiddleware.msAuthenticator,
          tenantType: TenantType.entraIDAndMicrosoftAccount,
        ),
      );
final account = await msalAuth.acquireToken(); //(excaption string)
```

AppDelegat
```
import UIKit
import Flutter
import MSAL

@main
@objc class AppDelegate: FlutterAppDelegate {
   override func application(
     _ application: UIApplication,
     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
   ) -> Bool {
     GeneratedPluginRegistrant.register(with: self)
     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
   }

    override func application(
        _ app: UIApplication,
        open url: URL,
        options: [UIApplication.OpenURLOptionsKey : Any] = [:]
    ) -> Bool {
    guard let sourceApplication = options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String else {
        return false
    }
    return MSALPublicClientApplication.handleMSALResponse(url, sourceApplication: sourceApplication)
    }
}
```

What are I doing wrong?
Please, help)

**Comment by sushil7271** [comment]
I'm experiencing the same issue too. Have you found any possible workarounds for it?
`  return MsalAuth.createPublicClientApplication(
      clientId: <clientId>,
      scopes: <scopes>,
      loginHint: 'login hint string',
      androidConfig: AndroidConfig(
        configFilePath: 'assets/msal_config.json',
        tenantId: <tenantId>,
      ),
      iosConfig: IosConfig(
          authority: https://<host>/tfp/<tenant>/<policy>,
          authMiddleware: AuthMiddleware.webview,
          tenantType: TenantType.azureADB2C),
    );`

**Comment by Chirag-Pernix** [comment]
+1

**Comment by nayanAubie** [comment]
@levmorgot @sushil7271 Have you added keychain group in iOS from Xcode? -- `com.microsoft.adalcache`

**Comment by levmorgot** [comment]
I solved my problem
in fact it was my mistake 
since I had also connected Google authorization before, then I added parameters to Info.plist for it and after that I didn’t notice that I was duplicating these parameters for msal, thereby overwriting them

**Then**
...
\<key>CFBundleURLTypes\</key>
        \<array>
        	\<dict>
        		\<key>CFBundleURLSchemes\</key>
        		\<array>
        			\<string>msauth.$(PRODUCT_BUNDLE_IDENTIFIER)\</string>
        		\</array>
        	\</dict>
        \</array>
        \<key>LSApplicationQueriesSchemes\</key>
        \<array>
        	\<string>msauthv2\</string>
        	\<string>msauthv3\</string>
        \</array>
...
\<key>CFBundleURLTypes\</key>
        \<array>
        	\<dict>
        		\<key>CFBundleTypeRole\</key>
        		\<string>Editor\</string>
        		\<key>CFBundleURLSchemes\</key>
        		\<array>
        			\<string>com.googleusercontent.apps.2e23d\</string>
        		\</array>
        	\</dict>
        \</array>
...

**Now**
...
\<key>CFBundleURLTypes\</key>
        \<array>
        	\<dict>
        		\<key>CFBundleTypeRole\</key>
        		\<string>Editor\</string>
        		\<key>CFBundleURLSchemes\</key>
        		\<array>
        			\<string>com.googleusercontent.apps5y5\</string>
        			\<string>msauth.$(PRODUCT_BUNDLE_IDENTIFIER)\</string>
        		\</array>
        	\</dict>
        \</array>
        \<key>LSApplicationQueriesSchemes\</key>
                \<array>
                	\<string>msauthv2\</string>
                	\<string>msauthv3\</string>
                \</array>
...

**Comment by nayanAubie** [comment]
@levmorgot thanks for the clarification.

**Comment by sushil7271** [comment]
> @levmorgot @sushil7271 Have you added keychain group in iOS from Xcode? -- `com.microsoft.adalcache`

Yes, I have added a keychain group `com.microsoft.adalcache`

**Comment by nayanAubie** [comment]
@sushil7271 please share the proper code snippet if you are still facing an issue.
