### ISSUE TITLE
When I run it, I encounter this exception and haven't been able to fix it. Is there any step I might have missed?

### ISSUE THREAD

**Issue by canred** [nayanAubie/msal_auth#32]
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing D:\flutter-project\msal_auth-main\msal_auth-main\example\android\app\src\main\AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Error: Gradle task assembleDebug failed with exit code 1

When I remove  "<activity android:name="com.microsoft.identity.client.BrowserTabActivity">  from "D:\flutter-project\msal_auth-main\msal_auth-main\example\android\app\src\main\AndroidManifest.xml"
it is compile well ...
 Is there any step I might have missed? 
Please help me ~~~

**Comment by nayanAubie** [comment]
Have you changed anything in the default project?
