### ISSUE TITLE
Msal exception with error: Account identifier

### ISSUE THREAD

**Issue by Tauheed** [nayanAubie/msal_auth#35]
After successful login when trying to logout or fetching silent token using the given sample function getting this error **(Msal exception with error: Account identifier)**.

Future<void> logout() async {
    try {
      final msalAuth = await getMsalAuth();
      await msalAuth.logout();
    } on MsalException catch (e) {
      log('Msal exception with error: ${e.errorMessage}');
    } catch (e) {
      log(e.toString());
    }
  }

**Comment by nayanAubie** [comment]
@Tauheed @SamGustinHdr have you checked the example app? it is completely working. probably issue in your code management.

**Comment by SamGustinHdr** [comment]
@nayanAubie you are right. issue on my side, thanks!

**Comment by nayanAubie** [comment]
@Tauheed I think you have not added keychain group `com.microsoft.adalcache` in your iOS project capabilities. this issue does not happen on Android.

**Comment by Tauheed** [comment]
> @Tauheed I think you have not added keychain group `com.microsoft.adalcache` in your iOS project capabilities. this issue does not happen on Android.

@nayanAubie  Yes, this was the issue. Working now thanks. But would be good to mention in the document too.

**Comment by nayanAubie** [comment]
@Tauheed it is already there in doc. please check.
