### ISSUE TITLE
Add optional loginHint to acquireToken

### ISSUE THREAD

**Issue by paolomastinuspindox** [nayanAubie/msal_auth#39]
We can add loginHint when calling acquireToken and not on createPublicClientApplication

**Comment by nayanAubie** [comment]
@paolomastinuspindox Could you share any specific reason why to add `loginHint` on `acquireToken` method?

**Comment by paolomastinuspindox** [comment]
> @paolomastinuspindox Got it. I'll update it soon.

If you need it I'll give you my updated files:

`public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult)
    {
        //get the arguments as a dictionary
        guard let dict = call.arguments as? NSDictionary else { return }
        let scopes = dict["scopes"] as? [String] ?? [String]()
        let clientId = dict["clientId"] as? String ?? ""
        let authority = dict["authority"] as? String ?? ""
        let authMiddleware = dict["authMiddleware"] as? String ?? ""
        let tenantType = dict["tenantType"] as? String ?? ""
        let loginHint = dict["loginHint"] as? String ?? ""
        
        switch( call.method ){
        case "initialize": initialize(clientId: clientId, authority: authority, authMiddleware: authMiddleware, tenantType: tenantType, loginHint: loginHint, result: result)
        **case "acquireToken": acquireToken(scopes: scopes, result: result, loginHint: loginHint)**
        case "acquireTokenSilent": acquireTokenSilent(scopes: scopes, result: result)
        case "logout": logout(result: result)
        default: result(FlutterMethodNotImplemented)
        }
    }`

`extension MsalAuthPlugin {
    
    private func acquireToken(scopes: [String], result: @escaping FlutterResult, **loginHint: String**)
    {
        if let application = getApplication(result: result){
            
            guard let viewController = UIViewController.keyViewController else { return }
            let webViewParameters = MSALWebviewParameters(authPresentationViewController: viewController)
            if #available(iOS 13.0, *) {
                webViewParameters.prefersEphemeralWebBrowserSession = true
                webViewParameters.webviewType = MsalAuthPlugin.authMiddleware != "webView" ? MSALWebviewType.safariViewController : MSALWebviewType.wkWebView
            }
            
            removeAccount(application)
            
            let interactiveParameters = MSALInteractiveTokenParameters(scopes: scopes, webviewParameters: webViewParameters)
            interactiveParameters.promptType = MSALPromptType.login

            **if (MsalAuthPlugin.loginHint != "" || loginHint != "") {**
                interactiveParameters.loginHint = MsalAuthPlugin.loginHint
            }`

And in your flutter app you can call something like

`Future<MsalUser?> acquireToken(**String? loginHint**) async {
    try {
      assert(_scopes.isNotEmpty, 'Scopes can not be empty');
      final arguments = <String, dynamic>{'scopes': _scopes};
      **arguments['loginHint'] ??= loginHint;**
      final json = await _methodChannel.invokeMethod('acquireToken', arguments);
      if (json != null) {
        return MsalUser.fromJson(jsonDecode(json));
      }
      return null;
    } on PlatformException catch (e) {
      throw e.msalException;
    }
  }`

Hope it helps.

**Comment by nayanAubie** [comment]
@paolomastinuspindox Fixed in version `2.2.0`
