### ISSUE TITLE
login find

### ISSUE THREAD

**Issue by Digvijaysinh-Sapphire** [nayanAubie/msal_auth#47]
How do we find whether the user is login or not 
the issue is that is not asking every time the login prompt how to achieve this by asking every time for login credentials or selecting an account

**Comment by nayanAubie** [comment]
The `acquireToken` method has a `prompt` option that you can modify as needed. to check the active session, you can call `currentAccount` method for single account mode, `getAccounts` method for multiple account mode.

**Comment by Digvijaysinh-Sapphire** [comment]
after login uninstall the app and reinstall the app. The issue is after calling acquireToken this will automatically login without  login credentials or selecting an account this is not right without information how to currentAccount  or direct call signout 
 get a direct call to throw an issue not an account @nayanAubie
