### ISSUE TITLE
acquireTokenSilent throws an error

### ISSUE THREAD

**Issue by jakuste136** [nayanAubie/msal_auth#5]
When I run the code from the example and hit the button 'Get Token silent' application closes and I can see an error in the console:
E/AndroidRuntime(25324): java.lang.IllegalArgumentException: Unsupported value: '[Ljava.lang.StackTraceElement;@526ae04' of type 'class [Ljava.lang.StackTraceElement;'
E/AndroidRuntime(25324): 	at t3.p.p(Unknown Source:444)
E/AndroidRuntime(25324): 	at t3.q.d(Unknown Source:37)
E/AndroidRuntime(25324): 	at t3.j$a$a.b(Unknown Source:10)
E/AndroidRuntime(25324): 	at u0.a$c.onError(Unknown Source:39)
E/AndroidRuntime(25324): 	at com.microsoft.identity.client.PublicClientApplication$19.onError(Unknown Source:8)
E/AndroidRuntime(25324): 	at com.microsoft.identity.client.PublicClientApplication$19.onError(Unknown Source:2)
E/AndroidRuntime(25324): 	at com.microsoft.identity.client.PublicClientApplication$16$1.run(Unknown Source:4)
E/AndroidRuntime(25324): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(25324): 	at android.os.Handler.dispatchMessage(Handler.java:99)

**Comment by nayanAubie** [comment]
Let me check, @jakuste136. Probably a recent update has caused this problem.

**Comment by nayanAubie** [comment]
It's completely working. maybe you are missing one of the following changes:
- Replace `host` and `path` in `AndroidManifest.xml`.
- Add the proper value of `redirect_uri` in `msal_config.json`
- Add the proper value of `_clientId` and `TENANT_ID` in `main.dart`
